import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden min-h-screen bg-zinc-800`}
      >
        <div className="flex flex-col">
          <ClerkProvider>
            <header className="flex justify-end items-center p-4 gap-4 h-16 bg-white border-b border-[#E4E4E7]">
              <Show when="signed-out">
                <div className="flex items-center gap-3">
                  <div className="rounded-xl border border-zinc-200 p-2 hover:bg-neutral-700 hover:text-white cursor-pointer transition-colors duration-300">
                    <SignInButton />
                  </div>
                  <p>Or</p>
                  <div className="rounded-xl border border-zinc-200 p-2 hover:bg-neutral-700 hover:text-white cursor-pointer transition-colors duration-300">
                    <SignUpButton />
                  </div>
                </div>
              </Show>
              <Show when="signed-in">
                <div className="w-full flex justify-between items-center">
                  <h1 className="font-medium text-[24px]">Quiz app</h1>
                  <div className="w-fit h-fit">
                    <UserButton />
                  </div>
                </div>
              </Show>
            </header>

            <SidebarProvider
              defaultOpen={false}
              style={
                {
                  "--sidebar-width-icon": "72px",
                } as React.CSSProperties
              }
            >
              <AppSidebar />
              <main>{children}</main>
            </SidebarProvider>
          </ClerkProvider>
        </div>
      </body>
    </html>
  );
}
