import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/app-sidebar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <div className="flex flex-col h-screen">
            <header className="flex justify-end items-center p-4 h-16 bg-white border-b border-zinc-200 shrink-0 text-black fixed w-full">
              <Show when="signed-out">
                <div className="flex items-center gap-3">
                  <SignInButton />
                  <p>Or</p>
                  <SignUpButton />
                </div>
              </Show>
              <Show when="signed-in">
                <div className="w-full flex justify-between items-center">
                  <Link href={"/"}>
                    <h1 className="font-medium text-[24px]">Quiz app</h1>
                  </Link>

                  <UserButton />
                </div>
              </Show>
            </header>

            <SidebarProvider
              defaultOpen={false}
              style={{ "--sidebar-width-icon": "72px" } as React.CSSProperties}
            >
              <div className="flex flex-1 overflow-hidden">
                <AppSidebar />
                <main className="flex-1 overflow-y-auto">{children}</main>
              </div>
            </SidebarProvider>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
